set(MATRIX_NAME "matrix")
set(MATRIX_VERSION_MAJOR 1)
set(MATRIX_VERSION_NUMBER_MAJOR ${MATRIX_VERSION_MAJOR})
set(MATRIX_VERSION_MINOR 0)
set(MATRIX_VERSION_NUMBER_MINOR ${MATRIX_VERSION_MINOR})
set(MATRIX_VERSION_PATCH 0)
set(MATRIX_VERSION_NUMBER_PATCH ${MATRIX_VERSION_PATCH})

if (MATRIX_VERSION_MAJOR LESS 10)
    set(MATRIX_VERSION_NUMBER_MAJOR "${MATRIX_VERSION_MAJOR}0")
endif (MATRIX_VERSION_MAJOR LESS 10)

if (MATRIX_VERSION_MINOR LESS 10)
    set(MATRIX_VERSION_NUMBER_MINOR "0${MATRIX_VERSION_MINOR}")
endif (MATRIX_VERSION_MINOR LESS 10)

if (MATRIX_VERSION_NUMBER_PATCH LESS 100)
    if (MATRIX_VERSION_NUMBER_PATCH GREATER 10)
        set(MATRIX_VERSION_NUMBER_PATCH "0${MATRIX_VERSION_PATCH}")
    else ()
        set(MATRIX_VERSION_NUMBER_PATCH "00${MATRIX_VERSION_PATCH}")
    endif (MATRIX_VERSION_NUMBER_PATCH GREATER 10)
endif (MATRIX_VERSION_NUMBER_PATCH LESS 100)

set(
    MATRIX_VERSION_NUMBER
    "${MATRIX_VERSION_NUMBER_MAJOR}${MATRIX_VERSION_NUMBER_MINOR}${MATRIX_VERSION_NUMBER_PATCH}"
)

set(MATRIX_VERSION "${MATRIX_VERSION_MAJOR}.${MATRIX_VERSION_MINOR}.${MATRIX_VERSION_PATCH}")
set(MATRIX_STRING "${MATRIX_NAME} ${MATRIX_VERSION}")
set(MATRIX_TARNAME "${MATRIX_NAME}-${MATRIX_VERSION}")
set(MATRIX_BUGREPORT "https://github.com/quantmatrix/matrix/issues")
set(MATRIX_DESCRIPTION "You had me at hello !")
set(MATRIX_URL "http://www.quantmatrix.org/matrix")
set(MATRIX_EXECUTABLE "matrix")

set(MATRIX_SRC_CORE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/core")
set(MATRIX_SRC_OS_UNIX_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/os/unix")
set(MATRIX_SRC_OS_WIN32_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/os/win32")

set(MATRIX_CURRENT_PLATFORM "POSIX")

set(MATRIX_SRC_OS_DIR "${MATRIX_SRC_OS_UNIX_DIR}")